"""Maps an environment `Observation` plus an organism's own internal
proprioceptive state into the flat vector its controller consumes.

Proprioception (own energy, last action taken) is generated by the
organism itself, not the environment — it is information the organism is
entitled to (it's about *itself*), distinct from both environment-sensed
information and simulator-hidden state.
"""

from __future__ import annotations

import numpy as np

from genevra.arrays import FloatArray
from genevra.simulation.types import Action, Observation

_ENERGY_SCALE = 10.0


class SensorSystem:
    def __init__(self, view_radius: int, channels: int = 2) -> None:
        """`channels` is the number of feature planes in the local grid a
        given environment produces — 2 for `GridWorld` (obstacle,
        resource), 3 for `SharedGridWorld` (obstacle, resource A,
        resource B). Defaults to 2 so every Phase 1-4 caller is
        unaffected."""
        if view_radius < 0:
            raise ValueError("view_radius must be >= 0")
        if channels <= 0:
            raise ValueError("channels must be positive")
        window_size = 2 * view_radius + 1
        self._grid_features = window_size * window_size * channels

    @property
    def output_size(self) -> int:
        return self._grid_features + 2  # + own energy + last action

    def encode(
        self, observation: Observation, own_energy: float, last_action: Action | None
    ) -> FloatArray:
        grid = observation.local_grid.reshape(-1).astype(np.float32)
        if grid.shape != (self._grid_features,):
            raise ValueError(
                f"observation.local_grid has {grid.shape} features, "
                f"expected ({self._grid_features},)"
            )
        energy_signal = np.array([np.tanh(own_energy / _ENERGY_SCALE)], dtype=np.float32)
        action_value = float(last_action) / len(Action) if last_action is not None else 0.0
        action_signal = np.array([action_value], dtype=np.float32)
        result: FloatArray = np.concatenate([grid, energy_signal, action_signal])
        return result
